# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-11-07 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20191106_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='total_cart_price',
            new_name='total_cart',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='total_item_price',
            new_name='total_item',
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_items',
            field=models.ManyToManyField(blank=True, to='myapp.CartItem'),
        ),
    ]
