# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-11-24 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bying_type',
            field=models.CharField(choices=[('Самовивіз', 'Самовивіз'), ('Доставка', 'Доставка')], default='Самовивіз', max_length=50),
        ),
    ]
