# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-11-24 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20191124_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='bying_type',
            new_name='buying_type',
        ),
    ]
