# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-11-24 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20191124_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cart_items',
            new_name='items',
        ),
    ]
