# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-11-24 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20191124_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В обробці', 'В обробці'), ('Виконується', 'Виконується'), ('Оплачений', 'Оплачений')], default='В обробці', max_length=120),
        ),
    ]
