# Generated by Django 2.2.7 on 2019-12-04 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20191129_0655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.AlterField(
            model_name='order',
            name='buying_type',
            field=models.CharField(choices=[('By yourself', 'By yorself'), ('Delievery', 'Delievery')], default='By yourself', max_length=50),
        ),
    ]
